# -*- coding: utf-8 -*-
"""cohort_for_git

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1J4Ut5F9BOJLxjYEmYp-wBxbXsKAhbWms

## Загружаем данные.
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
# %load_ext google.colab.data_table
from vega_datasets import data

"""https://drive.google.com/file/d/1br8a4UBe8GIW3vIRFIPNpOk7J3PNm_OH/view?usp=sharing

https://drive.google.com/file/d/1-Fjs44hO-O1iM_GGGGiraViqvAc9WKdq/view?usp=sharing
"""

!gdown --id 1br8a4UBe8GIW3vIRFIPNpOk7J3PNm_OH
!gdown --id 1-Fjs44hO-O1iM_GGGGiraViqvAc9WKdq

df1 = pd.read_csv('/content/olist_orders_dataset.csv')
df2 = pd.read_csv('/content/olist_order_payments_dataset.csv')

df = df1.merge(df2,on = 'order_id')

df.head()

df.info()

df['order_purchase_timestamp'] = pd.to_datetime(df['order_purchase_timestamp'])

df['date'] = df['order_purchase_timestamp'].dt.strftime('%Y-%m')

min_user_date = df.groupby('customer_id')['date'].min()

df = df.merge(min_user_date,on='customer_id',suffixes=('_', 'min'))

df.groupby(['datemin', 'date_'])\
['customer_id','payment_value','order_id'].agg(
    {'customer_id': pd.Series.nunique,
        'payment_value': 'sum',
          'order_id': 'count'})

cohorts

